jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 120
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - task: MSBuild@0
    inputs:
      clean: false
  - script: |
      pip install bincrafters-package-tools conan-package-tools conan
      python build.py
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      CONAN_TOTAL_PAGES: 4
  strategy:
    matrix:
      MinGW GCC 6 PAGE 1:
         MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
         CONAN_CURRENT_PAGE: 1
         CONAN_TOTAL_PAGES: 2
      MinGW GCC 6 PAGE 2:
         MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
         CONAN_CURRENT_PAGE: 2
         CONAN_TOTAL_PAGES: 2

      MinGW GCC 7 PAGE 1:
         MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
         CONAN_CURRENT_PAGE: 1
         CONAN_TOTAL_PAGES: 2
      MinGW GCC 7 PAGE 2:
         MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
         CONAN_CURRENT_PAGE: 2
         CONAN_TOTAL_PAGES: 2

      Visual Studio 2017 14.0 PAGE 1:
        CONAN_VISUAL_VERSIONS: "14"
        CONAN_CURRENT_PAGE: 1
      Visual Studio 2017 14.0 PAGE 2:
        CONAN_VISUAL_VERSIONS: "14"
        CONAN_CURRENT_PAGE: 2
      Visual Studio 2017 14.0 PAGE 3:
        CONAN_VISUAL_VERSIONS: "14"
        CONAN_CURRENT_PAGE: 3
      Visual Studio 2017 14.0 PAGE 4:
        CONAN_VISUAL_VERSIONS: "14"
        CONAN_CURRENT_PAGE: 4

      Visual Studio 2017 15.0 PAGE 1:
        CONAN_VISUAL_VERSIONS: "15"
        CONAN_CURRENT_PAGE: 1
      Visual Studio 2017 15.0 PAGE 2:
        CONAN_VISUAL_VERSIONS: "15"
        CONAN_CURRENT_PAGE: 2
      Visual Studio 2017 15.0 PAGE 3:
        CONAN_VISUAL_VERSIONS: "15"
        CONAN_CURRENT_PAGE: 3
      Visual Studio 2017 15.0 PAGE 4:
        CONAN_VISUAL_VERSIONS: "15"
        CONAN_CURRENT_PAGE: 4

- job: MSVC12
  pool:
    vmImage: 'vs2015-win2012r2'
  timeoutInMinutes: 120
  steps:
  - script: |
      pip install bincrafters-package-tools conan-package-tools conan
      python build.py
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      CONAN_TOTAL_PAGES: 4
  strategy:
    matrix:
      Visual Studio 2015 12.0 PAGE 1:
        CONAN_VISUAL_VERSIONS: "12"
        CONAN_CURRENT_PAGE: 1
      Visual Studio 2015 12.0 PAGE 2:
        CONAN_VISUAL_VERSIONS: "12"
        CONAN_CURRENT_PAGE: 2
      Visual Studio 2015 12.0 PAGE 3:
        CONAN_VISUAL_VERSIONS: "12"
        CONAN_CURRENT_PAGE: 3
      Visual Studio 2015 12.0 PAGE 4:
        CONAN_VISUAL_VERSIONS: "12"
        CONAN_CURRENT_PAGE: 4
