jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 120
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: |
      pip install bincrafters-package-tools conan-package-tools conan
      python build.py
    env:
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  strategy:
    matrix:
      Visual Studio 2015 14.0:
        CONAN_VISUAL_VERSIONS: "14"
      Visual Studio 2017 15.0:
        CONAN_VISUAL_VERSIONS: "15"
      Visual Studio 2014 12.0:
        pool:
          vmImage: 'vs2015-win2012r2'
        CONAN_VISUAL_VERSIONS: "12"
